--BEGIN;

-- DROP TABLES

DROP TABLE IF EXISTS Nationalities CASCADE;
DROP TABLE IF EXISTS People CASCADE;
DROP TABLE IF EXISTS Categories CASCADE;
DROP TABLE IF EXISTS Places CASCADE;
DROP TABLE IF EXISTS Events CASCADE;
DROP TABLE IF EXISTS Teams CASCADE;
DROP TABLE IF EXISTS Events_additional_info CASCADE;
DROP TABLE IF EXISTS Records CASCADE; 
DROP TABLE IF EXISTS Results CASCADE;
DROP TABLE IF EXISTS competitor_to_team CASCADE;
DROP TABLE IF EXISTS Team_to_Event CASCADE;
DROP TABLE IF EXISTS decisions CASCADE;
DROP TABLE IF EXISTS Disciplines CASCADE;
DROP TABLE IF EXISTS Medals CASCADE;

--DROP VIEW

DROP VIEW MedalsByNationality CASCADE;
DROP VIEW MedalsByCompetitors CASCADE;

DROP TYPE IF EXISTS result_type CASCADE;
-- DROP SEQUENCES
DROP SEQUENCE IF EXISTS person_seq CASCADE;
DROP SEQUENCE IF EXISTS idividual_seq CASCADE;
DROP SEQUENCE IF EXISTS team_seq CASCADE;
DROP SEQUENCE IF EXISTS category_seq CASCADE;
DROP SEQUENCE IF EXISTS event_seq CASCADE;

--DROP FUNCTIONS

DROP FUNCTION IF EXISTS rand_daterand_date(frommm date, tooo date) CASCADE;
DROP FUNCTION IF EXISTS rand_nationality() CASCADE;
DROP FUNCTION IF EXISTS rand_surname() CASCADE;
DROP FUNCTION IF EXISTS rand_name() CASCADE;
DROP FUNCTION IF EXISTS insert_and_assaign_random_team(competitionid int) CASCADE;
DROP FUNCTION IF EXISTS getRanking_Teams(categoryId int, type result_type) CASCADE;
DROP FUNCTION IF EXISTS getRanking_People(categoryId int, type result_type) CASCADE; 


--COMMIT;
-- 

